# Generated by Django 3.1.7 on 2021-02-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000, verbose_name='Задача')),
                ('status', models.CharField(default='Unknown', max_length=200, verbose_name='Статус')),
                ('time', models.CharField(blank=True, default='New', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Статус',
                'db_table': 'articles',
            },
        ),
    ]
