# Generated by Django 3.1.7 on 2021-02-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210225_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
